### PR TITLE
add integration tests

### PR DESCRIPTION
**Pull request by SimeonEhrig**

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
@szabo137 @AntonReinhard can anybody verify, that it is correct, that integration tests are generated for QED processes, fields and events.

I also think, that it is working correctly. Looks like there are bugs in QED events and processes.

**Comment by AntonReinhard** [comment]
> @szabo137 @AntonReinhard can anybody verify, that it is correct, that integration tests are generated for QED processes, fields and events.
> 
> I also think, that it is working correctly. Looks like there are bugs in QED events and processes.

Looks good so far, the test failures in events and processes are caused by a double export which is resolved with https://github.com/QEDjl-project/QEDprocesses.jl/pull/74

**Comment by AntonReinhard** [comment]
I have rebased the branch onto the newest dev branch, so it should build now.

**Comment by AntonReinhard** [comment]
Will fix #17

**Review by szabo137 — APPROVED** [review]
Thanks for this! Looks good for me.

**Pull request merged**
