### PR TITLE
Add CompatHelper

### PR DESCRIPTION
**Pull request by AntonReinhard**
Adds the compat helper workflow. I also set up the deploy key and the private key secret.

### CODE REVIEW

**Comment by AntonReinhard** [comment]
Closes #5

**Comment by AntonReinhard** [comment]
I have added the TagBot too

**Comment by SimeonEhrig** [comment]
Did you tested the jobs somewhere?

**Comment by SimeonEhrig** [comment]
If saw, that the code is working in QuantumElectrodynamics.jl

**Review by SimeonEhrig — APPROVED** [review]

**Pull request merged**
