### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by szabo137**
Add changes from release branch 0.1.0 back to dev. 

don't forget: **no squishing**

### CODE REVIEW

**Review by AntonReinhard — APPROVED** [review]
:+1:

**Comment by AntonReinhard** [comment]
I can't merge this because my approval doesn't count since I'm the last pusher...

**Comment by szabo137** [comment]
Me neither, because I am the creator of this 🤷‍♂️
@SimeonEhrig @steindev would some of you be so kind and hit the approve button. 

IMPORTANT: in the case of merging, please do **not** squash the commits. This would destroy the sync of main and dev, which causes some trouble for the next release.

**Review by SimeonEhrig — APPROVED** [review]

**Comment by SimeonEhrig** [comment]
@szabo137 Which merge should I do? `Create a merge commit` or `rebase and merge`?

**Comment by szabo137** [comment]
> @szabo137 Which merge should I do? `Create a merge commit` or `rebase and merge`? 

@SimeonEhrig best is `create a merge commit`, thanks 🙏

**Pull request merged**
